name: AutoBuild
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          dockerfile: Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/votes-backend:${{ github.sha }}
      - name: Deploy to
          acme.com/v1/webservices/staging.kblocks.io/default/shai-a-votes-be-webservice
        run: "curl -X PATCH -H \"content-type: application/json\"
          https://staging.kblocks.io/api/resources/acme.com/v1/webservices/stag\
          ing.kblocks.io/default/shai-a-votes-be-webservice -d
          '{\"source\":{\"fromImage\":{\"image\":\"${{ secrets.DOCKER_USERNAME
          }}/votes-backend:${{ github.sha }}\"}}}'"
